[oai_dc]
metadataPrefix="oai_dc"
schema="http://www.openarchives.org/OAI/2.0/oai_dc.xsd"
metadataNamespace="http://www.openarchives.org/OAI/2.0/oai_dc/"
rdfProperty=""
class="\\acdhOeaw\oai\DcMetadata"

[cmdi_collection]
metadataPrefix="cmdi_collection"
schema="http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_1345561703620/xsd"
metadataNamespace="http://www.clarin.eu/cmd/"
rdfProperty="https://vocabs.acdh.ac.at/#hasCMDIcollection"
class="\\acdhOeaw\oai\ResMetadata"

[cmdi_lexRes]
metadataPrefix="cmdi_lexRes"
schema="http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_1290431694579/xsd"
metadataNamespace="http://www.clarin.eu/cmd/"
rdfProperty="https://vocabs.acdh.ac.at/#hasCMDIlexRes"
class="\\acdhOeaw\oai\ResMetadata"

[cmdi_teiHdr]
metadataPrefix="cmdi_teiHdr"
schema="http://www.clarin.eu/cmd/ http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_1380106710826/xsd"
metadataNamespace="http://www.clarin.eu/cmd/"
rdfProperty="https://vocabs.acdh.ac.at/#hasCMDIteiHdr"
class="\\acdhOeaw\oai\ResMetadata"

[cmdi_textCorpus]
metadataPrefix="cmdi_textCorpus"
schema="http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_1290431694580/xsd"
metadataNamespace="http://www.clarin.eu/cmd/"
rdfProperty="https://vocabs.acdh.ac.at/#hasCMDItextCorpus"
class="\\acdhOeaw\oai\ResMetadata"

[cmdi_frequencyList]
metadataPrefix="cmdi_frequencyList"
schema="http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_1357720977490/xsd"
metadataNamespace="http://www.clarin.eu/cmd/"
rdfProperty="https://vocabs.acdh.oeaw.ac.at/#hasCMDIfrequencyList"
class="\\acdhOeaw\oai\ResMetadata"

