name: test
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: php
        uses: shivammathur/setup-php@v2
        with:
         php-version: '8.2'
         extensions: mbstring, xml
      - name: composer
        run: |
          composer update
      - name: test
        run: |
          vendor/bin/phpunit

