name: deploy on rancher
on:
  workflow_dispatch: ~
  release:
    types: [published]
env:
  RANCHER_API_BASE: https://rancher.acdh-dev.oeaw.ac.at/v3
  RANCHER_PROJECT: Dissemination services
  RANCHER_NAMESPACE: arche-biblatex
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          composer update
          vendor/bin/phpunit tests
      - name: composer
        run: |
          composer update
      - name: test
        run: |
          vendor/bin/phpunit

